name = "hw1"
version = "0.1.0"
description = "Simplified nl, tail and wc utilities"
requires-python = ">=3.10"
authors = [
    { name = "Ilya Sarantsev", email = "minidoc004@gmail.com" },
]
keywords = [ "nl", "tail", "wc", "cli" ]
