FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    texlive-latex-base \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install fonarmeister_latex_helper

COPY main.py /app/main.py
COPY pic.png /app/pic.png
RUN mkdir /app/artifacts

WORKDIR /app

CMD ["python3", "main.py"]